
name: Generate Devstack VM

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt-get -y update
        sudo apt-get -y install qemu qemu-system-x86

    - name: Generate Devstack VM
      run: |
        packer init .
        packer validate .
        PACKER_LOG=1 packer build -machine-readable -var headless=true .
    - name: Upload generated vm
      uses: actions/upload-artifact@v3
      with:
        name: devstack-bullseye.qcow2
        path: build